local path = core.get_modpath("va_weapons")
dofile(path .. "/api.lua")
dofile(path .. "/weapons/beam.lua")
dofile(path .. "/weapons/emp.lua")
dofile(path .. "/weapons/explosion.lua")
dofile(path .. "/weapons/flame.lua")
dofile(path .. "/weapons/laser.lua")
dofile(path .. "/weapons/lightning.lua")
dofile(path .. "/weapons/missile.lua")
dofile(path .. "/weapons/plasma.lua")
dofile(path .. "/weapons/railgun.lua")