local path = core.get_modpath("va_units")
dofile(path .. "/api.lua")
dofile(path .. "/t1/bot/vox_commander.lua")
dofile(path .. "/t1/bot/vox_constructor.lua")
dofile(path .. "/t1/bot/vox_repair.lua")
dofile(path .. "/t1/bot/vox_scout.lua")
dofile(path .. "/t1/bot/vox_fast_infantry.lua")
dofile(path .. "/t1/bot/vox_light_plasma.lua")
dofile(path .. "/t1/bot/vox_rocket.lua")
dofile(path .. "/t1/bot/vox_anti_swarm.lua")